### ISSUE TITLE
Wrong icons in terminal file manager

### ISSUE THREAD

**Issue by Sem1rose** [iconicFonts/if#107]
**Describe the bug**

Folders and some files are displayed as the wrong icons. 

**Expected behavior**

In a patched NF font, the correct icons are displayed, however when changing the terminal font, the wrong icons are displayed.

**Screenshots**

![screenshot-1730497230](https://github.com/user-attachments/assets/08211752-d4b7-4b08-9159-02308857afe6)

Fira code: wrong folder (top) and blank file (bottom) icons
![screenshot-1730497427](https://github.com/user-attachments/assets/22352ac3-9aff-4bfa-a117-d477540db8dd)

Cascadia code NF: the correct icons
![screenshot-1730497512](https://github.com/user-attachments/assets/10b49281-3051-4d9e-99a1-add8a5b75050)

**Additional context**

OS: Arch linux
Terminal: kitty
File manager: [Yazi](https://github.com/sxyazi/yazi)

**Comment by haithium** [comment]
@Sem1Rose Because IconicFonts is not compatible with NerdFonts yet #92. As a temporary solution, you can use the icons in this [config](https://github.com/yazi-rs/configs/blob/main/if/theme.toml).

![image](https://github.com/user-attachments/assets/b4fe2a00-ff62-45d7-b240-2716066d08f0)
